### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by jgribonvald** [ether/ep_subscript_and_superscript#11] opened 2021-05-19 11:00 UTC
Hi,
on etherpad 1.8.13 I'm getting these console message:
```
UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_subscript_and_superscript, function name: ep_subscript_and_superscript/static/js/index, hook: aceEditEvent): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior.
```

Is there something todo to avoid that ?

**Comment by rhansen** [comment] 2021-09-23 22:42
Duplicate of #14

**Closed by rhansen** 2021-09-23 22:42 UTC
